# Generated by Django 3.1.4 on 2020-12-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '관리자', 'verbose_name_plural': '관리자'},
        ),
        migrations.AlterModelTable(
            name='fcuser',
            table='Fcuser',
        ),
    ]
