# Generated by Django 3.1.4 on 2020-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20201227_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
