# Generated by Django 3.1.4 on 2020-12-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_fcuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='email',
            new_name='useremail',
        ),
    ]
